# Generated by Django 6.0.2 on 2026-02-28 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_bloodrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=50, unique=True)),
                ('donor_name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=5)),
                ('date_of_donation', models.DateField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(default='Thank you for saving lives', max_length=200)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='mainapp.donor')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
